/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ComponentType: typeof import('./src/models/moduleConfigModel')['ComponentType']
  const EffectScope: typeof import('vue')['EffectScope']
  const FeatureType: typeof import('./src/models/moduleConfigModel')['FeatureType']
  const Language: typeof import('./src/language/index')['Language']
  const LanguageNames: typeof import('./src/language/index')['LanguageNames']
  const ModuleType: typeof import('./src/models/moduleItemModel')['ModuleType']
  const PrincipalType: typeof import('./src/models/userProfileModel')['PrincipalType']
  const acceptHMRUpdate: typeof import('pinia')['acceptHMRUpdate']
  const computed: typeof import('vue')['computed']
  const createApp: typeof import('vue')['createApp']
  const createPinia: typeof import('pinia')['createPinia']
  const customRef: typeof import('vue')['customRef']
  const defineAsyncComponent: typeof import('vue')['defineAsyncComponent']
  const defineComponent: typeof import('vue')['defineComponent']
  const defineStore: typeof import('pinia')['defineStore']
  const effectScope: typeof import('vue')['effectScope']
  const en: typeof import('./src/language/en')['default']
  const getActivePinia: typeof import('pinia')['getActivePinia']
  const getCurrentInstance: typeof import('vue')['getCurrentInstance']
  const getCurrentScope: typeof import('vue')['getCurrentScope']
  const getDateMessage: typeof import('./src/utils/datetime')['getDateMessage']
  const getEnglishDate: typeof import('./src/utils/datetime')['getEnglishDate']
  const getGeoGraphyList: typeof import('./src/services/metaData-service')['getGeoGraphyList']
  const getIcon: typeof import('./src/utils/icon-transfer')['getIcon']
  const getModuleConfig: typeof import('./src/services/module-service')['getModuleConfig']
  const getModulesList: typeof import('./src/services/module-service')['getModulesList']
  const getWeekNo: typeof import('./src/utils/datetime')['getWeekNo']
  const h: typeof import('vue')['h']
  const hideLoading: typeof import('./src/utils/loading')['hideLoading']
  const http: typeof import('./src/http/index')['default']
  const i18n: typeof import('./src/language/index')['i18n']
  const inject: typeof import('vue')['inject']
  const isElement: typeof import('./src/utils/datacheck')['isElement']
  const isNil: typeof import('./src/utils/datacheck')['isNil']
  const isNull: typeof import('./src/utils/datacheck')['isNull']
  const isProxy: typeof import('vue')['isProxy']
  const isReactive: typeof import('vue')['isReactive']
  const isReadonly: typeof import('vue')['isReadonly']
  const isRef: typeof import('vue')['isRef']
  const isUndefined: typeof import('./src/utils/datacheck')['isUndefined']
  const isVoid: typeof import('./src/utils/datacheck')['isVoid']
  const login: typeof import('./src/services/login-service')['login']
  const mapActions: typeof import('pinia')['mapActions']
  const mapGetters: typeof import('pinia')['mapGetters']
  const mapState: typeof import('pinia')['mapState']
  const mapStores: typeof import('pinia')['mapStores']
  const mapWritableState: typeof import('pinia')['mapWritableState']
  const markRaw: typeof import('vue')['markRaw']
  const moduleId: typeof import('./src/constants/index')['moduleId']
  const nextTick: typeof import('vue')['nextTick']
  const onActivated: typeof import('vue')['onActivated']
  const onBeforeMount: typeof import('vue')['onBeforeMount']
  const onBeforeRouteLeave: typeof import('vue-router')['onBeforeRouteLeave']
  const onBeforeRouteUpdate: typeof import('vue-router')['onBeforeRouteUpdate']
  const onBeforeUnmount: typeof import('vue')['onBeforeUnmount']
  const onBeforeUpdate: typeof import('vue')['onBeforeUpdate']
  const onDeactivated: typeof import('vue')['onDeactivated']
  const onErrorCaptured: typeof import('vue')['onErrorCaptured']
  const onMounted: typeof import('vue')['onMounted']
  const onRenderTracked: typeof import('vue')['onRenderTracked']
  const onRenderTriggered: typeof import('vue')['onRenderTriggered']
  const onScopeDispose: typeof import('vue')['onScopeDispose']
  const onServerPrefetch: typeof import('vue')['onServerPrefetch']
  const onUnmounted: typeof import('vue')['onUnmounted']
  const onUpdated: typeof import('vue')['onUpdated']
  const onWatcherCleanup: typeof import('vue')['onWatcherCleanup']
  const parentId: typeof import('./src/constants/index')['parentId']
  const provide: typeof import('vue')['provide']
  const reactive: typeof import('vue')['reactive']
  const readonly: typeof import('vue')['readonly']
  const ref: typeof import('vue')['ref']
  const resolveComponent: typeof import('vue')['resolveComponent']
  const router: typeof import('./src/router/index')['default']
  const setActivePinia: typeof import('pinia')['setActivePinia']
  const setMapStoreSuffix: typeof import('pinia')['setMapStoreSuffix']
  const setupI18n: typeof import('./src/language/index')['setupI18n']
  const shallowReactive: typeof import('vue')['shallowReactive']
  const shallowReadonly: typeof import('vue')['shallowReadonly']
  const shallowRef: typeof import('vue')['shallowRef']
  const showLoading: typeof import('./src/utils/loading')['showLoading']
  const size: typeof import('./src/constants/index')['size']
  const storeToRefs: typeof import('pinia')['storeToRefs']
  const toRaw: typeof import('vue')['toRaw']
  const toRef: typeof import('vue')['toRef']
  const toRefs: typeof import('vue')['toRefs']
  const toValue: typeof import('vue')['toValue']
  const triggerRef: typeof import('vue')['triggerRef']
  const unref: typeof import('vue')['unref']
  const useAttrs: typeof import('vue')['useAttrs']
  const useCssModule: typeof import('vue')['useCssModule']
  const useCssVars: typeof import('vue')['useCssVars']
  const useI18n: typeof import('vue-i18n')['useI18n']
  const useId: typeof import('vue')['useId']
  const useLink: typeof import('vue-router')['useLink']
  const useModel: typeof import('vue')['useModel']
  const useModuleTabsStore: typeof import('./src/stores/moduleTabs')['useModuleTabsStore']
  const useRoute: typeof import('vue-router')['useRoute']
  const useRouter: typeof import('vue-router')['useRouter']
  const useSlots: typeof import('vue')['useSlots']
  const useTemplateRef: typeof import('vue')['useTemplateRef']
  const useUserProfileStore: typeof import('./src/stores/userProfile')['useUserProfileStore']
  const watch: typeof import('vue')['watch']
  const watchEffect: typeof import('vue')['watchEffect']
  const watchPostEffect: typeof import('vue')['watchPostEffect']
  const watchSyncEffect: typeof import('vue')['watchSyncEffect']
  const zh: typeof import('./src/language/zh')['default']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { Geography } from './src/models/metaDataModel'
  import('./src/models/metaDataModel')
  // @ts-ignore
  export type { Attribute, Feature, ModuleConfig } from './src/models/moduleConfigModel'
  import('./src/models/moduleConfigModel')
  // @ts-ignore
  export type { ModuleType, ModuleTab, ModuleItem } from './src/models/moduleItemModel'
  import('./src/models/moduleItemModel')
  // @ts-ignore
  export type { PrincipalType, Principal, UserProfile } from './src/models/userProfileModel'
  import('./src/models/userProfileModel')
  // @ts-ignore
  export type { Language } from './src/language/index'
  import('./src/language/index')
}
