/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ACheckboxGroup: typeof import('ant-design-vue/es')['CheckboxGroup']
    ACol: typeof import('ant-design-vue/es')['Col']
    ACollapse: typeof import('ant-design-vue/es')['Collapse']
    ACollapsePanel: typeof import('ant-design-vue/es')['CollapsePanel']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    ADropdownButton: typeof import('ant-design-vue/es')['DropdownButton']
    AdvancedSearch: typeof import('./src/components/advanced-search/AdvancedSearch.vue')['default']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ATree: typeof import('ant-design-vue/es')['Tree']
    ExportPanel: typeof import('./src/components/export-panel/ExportPanel.vue')['default']
    HeaderComponent: typeof import('./src/components/header/HeaderComponent.vue')['default']
    HistoryPanel: typeof import('./src/components/history-panel/HistoryPanel.vue')['default']
    InputSearch: typeof import('./src/components/input-search/InputSearch.vue')['default']
    ModuleContainer: typeof import('./src/components/module-container/ModuleContainer.vue')['default']
    ModuleContent: typeof import('./src/components/module-content/ModuleContent.vue')['default']
    ModulePage: typeof import('./src/components/module-page/ModulePage.vue')['default']
    ModuleTable: typeof import('./src/components/module-table/ModuleTable.vue')['default']
    MySelect: typeof import('./src/components/my-select/MySelect.vue')['default']
    ProvinceCity: typeof import('./src/components/province-city/ProvinceCity.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchResult: typeof import('./src/components/search-result/SearchResult.vue')['default']
    SelectPrincial: typeof import('./src/components/select-principal/SelectPrincial.vue')['default']
    SiderComponent: typeof import('./src/components/sider/SiderComponent.vue')['default']
  }
}
